//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        public int SupplyId { get; set; }
        public decimal Price { get; set; }
        public string Address { get; set; }
        public double Area { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual House House { get; set; }
        public virtual Land_plot Land_plot { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
