//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int DemandId { get; set; }
        public string Address { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public double MinArea { get; set; }
        public double MaxArea { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual HouseFilter HouseFilter { get; set; }
        public virtual LandPlotFilter LandPlotFilter { get; set; }
        public virtual FlatFilter FlatFilter { get; set; }
    }
}
