//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatFilter
    {
        public int DemandId { get; set; }
        public int MinFloor { get; set; }
        public int MaxFloor { get; set; }
        public int MinRoomCount { get; set; }
        public int MaxRoomCount { get; set; }
    
        public virtual Filter Filter { get; set; }
    }
}
