//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateAgencyEntities : DbContext
    {
        public static RealEstateAgencyEntities Instance { get; } = 
            new RealEstateAgencyEntities();
        protected RealEstateAgencyEntities()
            : base("name=RealEstateAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<Estate> Estate { get; set; }
        public virtual DbSet<Filter> Filter { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<FlatFilter> FlatFilter { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseFilter> HouseFilter { get; set; }
        public virtual DbSet<Land_plot> Land_plot { get; set; }
        public virtual DbSet<LandPlotFilter> LandPlotFilter { get; set; }
        public virtual DbSet<Realtor> Realtor { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
