//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> RealtorId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Estate Estate { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
